### ISSUE TITLE
Remove Pachyderm logo from datamesh-arch.png

### ISSUE THREAD

**Issue by MichaelTiemannOSC** [opendatahub-io-contrib/datamesh-platform#29]
The Pachyderm logo appears in this image:

https://github.com/opendatahub-io-contrib/datamesh-platform/blob/main/images/datamesh-arch.png

It should be removed and replaced with the new stack we will use for data versioning.

**Comment by jpaulrajredhat** [comment]
Pachyderm logo removed from architecture

**Comment by MichaelTiemannOSC** [comment]
Pachyderm still listed in the textual elaboration: Data Versioning and Lineage Management ([Pachyderm](https://www.pachyderm.com/))

Also a reminder that the Pachyderm project has been reincarnated here: https://docs.pachyderm.com/products/mldm/latest/sdk/ (FWIW).
