### ISSUE TITLE
Deploy simple Kafka cluster for integrate spark stream

### ISSUE THREAD

**Issue by jpaulrajredhat** [opendatahub-io-contrib/datamesh-platform#32]
Deploy Kafka cluster to test sprak structured streaming.

**Comment by mukesh1327** [comment]
Hi Jey, 

I have installed the Red Hat AMQ streams from operator hub and created a kafka cluster.
Kafka cluster is deployed in spark-datamesh-demo namespace with 3 instance and 25Gbi of persistent volume.

**Comment by jpaulrajredhat** [comment]
completed .
