### ISSUE TITLE
Upgrade metadata to latest version and integrate with airflow

### ISSUE THREAD

**Issue by caldeirav** [opendatahub-io-contrib/datamesh-platform#42]

**Comment by jpaulrajredhat** [comment]
Team @avinashsingh77 @Pujathacker2210 updatd OpenMeta to latest version 1.4.1. There is a issue connecting to airflow ingestion api. If any of you have time  , could you fix it when you guys get a chance.

**Comment by avinashsingh77** [comment]
Sure @jpaulrajredhat I will start taking a look at it

**Comment by jpaulrajredhat** [comment]
Open Metadata latest version 1.4.1 updated and integration with Airflow issue has been resolved. End to end pipeline working . Also Airflow python version updated to 3.10. 

@caldeirav let me know once tested so that I can close this issue.
