### ISSUE TITLE
Create lastest version of Trino Helm Chart to build auto deployment pipeline

### ISSUE THREAD

**Issue by jpaulrajredhat** [opendatahub-io-contrib/datamesh-platform#5]
Create Trino helm chart  to deploy Trino co-ordinator and minimum of 2 worker with Hive Meta-store service , Postgres Database. ZAGA team already has this on their instance. You can co-ordinate with Sharanya from ZAGA for any other information related to Trino helm chart

**Comment by Pujathacker2210** [comment]
@sharanyajune7 looks like you have deployed trino in this repo as well. Please confirm if anything is left to be done. Else, we can mark this issue as closed.

Cc @jpaulrajredhat @caldeirav

**Comment by jpaulrajredhat** [comment]
@Pujathacker2210 No one working on Helm chart other than you. Each component has two folder one for Helm and kustomize. Kustomize is the part of initial MVP which is already completed and tested. You can add your helm manifest  to Trion/helm folder.  
CC @caldeirav
